### ISSUE TITLE
Add actions

### ISSUE THREAD

**Issue by GabrielEValenzuela** [Esc-IngComp-UNC/computer-laboratory-web-page#11]
# Objective
Add automated actions to the repository for continuous integration (CI) to check the following:
1. **Building**: Ensure the project builds successfully for all commits and pull requests.
2. **Static Analysis**: Run linting and code quality checks.
3. **Coverage**: Generate and enforce test coverage thresholds.

## Deliverables
1. **CI Workflow: Build Check**
   - Implement a GitHub Actions workflow to:
     - Verify the build process on every push and pull request.
     - Test on multiple environments (e.g., Node.js versions `18`, `20`).

2. **CI Workflow: Static Analysis**
   - Run linting with ESLint to detect code quality issues.
   - Fail the workflow if any linting errors are detected.
   - Ensure consistent code style using Prettier:
     - Add a step to check Prettier formatting compliance.
   - Optionally configure additional static analysis tools (e.g., SonarCloud, CodeQL).

3. **CI Workflow: Test Coverage**
   - Use Jest (or equivalent) to:
     - Run tests and generate coverage reports.
     - Enforce minimum coverage thresholds (e.g., `80%` for statements, branches, and functions).
   - Upload test coverage reports as part of the CI workflow for visibility.

4. **Documentation**
   - Update the **README.md** to include a section on CI and coverage, with badges (e.g., build status, coverage).
   - Optionally add a **CONTRIBUTING.md** section explaining the CI process.

## Suggested Workflow Configuration
Example GitHub Actions workflow file:

```yaml
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format-check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
```

## Acceptance Criteria
- The CI pipeline successfully checks building, static analysis, and test coverage.
- The build step passes for all supported Node.js versions.
- Static analysis fails the pipeline if any linting or formatting issues are detected.
- Test coverage is reported and enforces the minimum threshold.
- Documentation is updated with CI details and relevant badges.
